apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../base

images:
- name: pacman2022/argocd-k8s
  newName: pacman2022/argocd-k8s
  newTag: 046db78533c0af4bd70d1017dda303fb12acbe2e
