apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../base

images:
- name: pacman2022/argocd-k8s
  newName: pacman2022/argocd-k8s
  newTag: 6b9b52b92236036ae5c757e58cd77ddc59fa9a76
