apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../base

images:
- name: pacman2022/argocd-k8s
  newName: pacman2022/argocd-k8s
  newTag: 1daecbe20dded31764d0f2ffa9d587369ab2ad87
