apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: "YXJnb2NkX2s4c19wd2Q="
  JWT_SECRET: "ZDA2NDJhMjcxNTc2ZDVmNTFkN2ZmNjE2MzE0NmQ5Zjc2ZTI5OGY0YjVmNjc4NzhiYWMwZTI2MDE5NmRlYTQyNQ=="
  DATABASE_URL: "cG9zdGdyZXNxbDovL2FyZ29jZF9rOHNfdXNlcjphcmdvY2RfazhzX3B3ZEBkYi1zZXJ2aWNlOjU0MzIvYXJnb2NkX2s4c19kYg=="